# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portal.models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='data_guru',
            fields=[
                ('id_guru', models.AutoField(primary_key=True, serialize=False)),
                ('nip_guru', models.CharField(max_length=120)),
                ('nama_guru', models.CharField(max_length=120)),
                ('pendidikan_guru', models.CharField(max_length=120)),
                ('jurusan_guru', models.CharField(max_length=120)),
                ('kelamin_guru', models.IntegerField(choices=[(1, 'perempuan'), (2, 'laki'), (3, 'not specified')], default=3)),
                ('pelajaran_guru', models.CharField(max_length=120)),
                ('foto_guru', models.ImageField(blank=True, help_text='Upload your photo for Avatar', null=True, upload_to='Foto_guru %Y %m %d')),
                ('updt', models.DateTimeField(auto_now=True)),
                ('tms', models.DateTimeField(auto_now_add=True)),
                ('publish_guru', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Detail data Guru',
                'verbose_name_plural': 'data Guru',
                'ordering': ['-updt', '-tms'],
            },
        ),
        migrations.CreateModel(
            name='data_kepala_sekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kep_sek', models.CharField(max_length=120)),
                ('nip_kep_sek', models.CharField(max_length=120)),
                ('foto_kep_sek', models.ImageField(blank=True, help_text='Upload your photo for Avatar', null=True, upload_to='Foto_kepala_sekolah %Y %m %d')),
                ('pesan_kep_sek', models.TextField()),
            ],
            options={
                'verbose_name': 'Detail Kepala Sekolah',
                'verbose_name_plural': 'Kepala Sekolah',
            },
        ),
        migrations.CreateModel(
            name='data_tu',
            fields=[
                ('id_tu', models.AutoField(primary_key=True, serialize=False)),
                ('nip_tu', models.CharField(max_length=120)),
                ('nama_tu', models.CharField(max_length=120)),
                ('pendidikan_tu', models.CharField(max_length=120)),
                ('jurusan_tu', models.CharField(max_length=120)),
                ('kelamin_tu', models.IntegerField(choices=[(1, 'perempuan'), (2, 'laki'), (3, 'not specified')], default=3)),
                ('pelajaran_tu', models.CharField(max_length=120)),
                ('foto_tu', models.ImageField(blank=True, help_text='Upload your photo for Avatar', null=True, upload_to='Foto_tu %Y %m %d')),
                ('updt', models.DateTimeField(auto_now=True)),
                ('tms', models.DateTimeField(auto_now_add=True)),
                ('publish_tu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Detail data Tu',
                'verbose_name_plural': 'data Tu',
                'ordering': ['-updt', '-tms'],
            },
        ),
        migrations.CreateModel(
            name='filex',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('nama_file', models.CharField(max_length=120)),
                ('dokumen_file', models.FileField(upload_to='Dokumen_file/')),
                ('updt', models.DateTimeField(auto_now=True)),
                ('tms', models.DateTimeField(auto_now_add=True)),
                ('publish_file', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Detail data File',
                'verbose_name_plural': 'data File',
                'ordering': ['-updt', '-tms'],
            },
        ),
        migrations.CreateModel(
            name='Home_Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Post Views',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('cover', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=portal.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', redactor.fields.RedactorField()),
                ('publish', models.BooleanField(default=True)),
                ('launching', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='silabus',
            fields=[
                ('id_silabus', models.AutoField(primary_key=True, serialize=False)),
                ('nama_silabus', models.CharField(max_length=120)),
                ('dokumen_silabus', models.FileField(upload_to='Dokumen_silabus/')),
                ('updt', models.DateTimeField(auto_now=True)),
                ('tms', models.DateTimeField(auto_now_add=True)),
                ('publish_silabus', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Detail data Silabus',
                'verbose_name_plural': 'data Silabus',
                'ordering': ['-updt', '-tms'],
            },
        ),
        migrations.CreateModel(
            name='siswa',
            fields=[
                ('id_siswa', models.AutoField(primary_key=True, serialize=False)),
                ('nis_siswa', models.CharField(max_length=120)),
                ('nama_siswa', models.CharField(max_length=120)),
                ('siswa_kelas', models.CharField(max_length=120)),
                ('kelamin_siswa', models.IntegerField(choices=[(1, 'perempuan'), (2, 'laki'), (3, 'not specified')], default=3)),
                ('siswa_jurusan', models.CharField(max_length=120)),
                ('foto_siswa', models.ImageField(blank=True, help_text='Upload your photo for Avatar', null=True, upload_to='Foto_siswa %Y %m %d')),
                ('updt', models.DateTimeField(auto_now=True)),
                ('tms', models.DateTimeField(auto_now_add=True)),
                ('publish_siswa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Detail data Siswa',
                'verbose_name_plural': 'data Siswa',
                'ordering': ['-updt', '-tms'],
            },
        ),
        migrations.AddField(
            model_name='home_views',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='portal.Post'),
        ),
    ]
