# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_saran',
            fields=[
                ('id_saran', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=120)),
                ('nomor_atau_email', models.CharField(max_length=120)),
                ('saran', models.TextField()),
                ('updt', models.DateTimeField(auto_now=True)),
                ('tms', models.DateTimeField(auto_now_add=True)),
                ('publish_saran', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'data saran',
                'verbose_name': 'Detail data saran',
                'ordering': ['-updt', '-tms'],
            },
        ),
    ]
